internalName: mdf_ru-win

locales:
  en:
    name: &bundleName "Moksha Keyboards"
    description: "Mobile OS keyboards for the Moksha language from the Divvun group at UiT."
  nb:
    name: "Moksha tastatur"
    description: "Mobiltastatur for Moksha fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [mdf-mob, mdf-mac, mdf-win]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.mdf
    icon: images/mdf-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.mdf
    bundleName: *bundleName
    icon: images/mdf-icon.png

  osx:
    <<: *AppleID
    icon: images/mdf-keyboard-menu-icon.png
    version: 0.1.1
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "DAD4B252-F7A3-4A97-9A9C-81A7A7D5FA47"
    
